meta_product_name: "Forget Me Not"
meta_title: "Forget Me Not - Meet Once, Remember Forever"
meta_description: "An app to store and monitor interactions with people"
meta_image: "networking.jpg"                       # should exist in `app/assets/images/`
